### PR TITLE
jsonpatcher: sort events by ts in the reducer

### PR DESCRIPTION
**Pull request by requilence**
Partially address #332 

Here is the example I had an issue with. It was solved by this PR. 
https://gist.github.com/requilence/a9d1c4ceab32e1f09b1ce2f3e895e242

It's too dumb to add it as a test, cause it can be false-positive. But maybe I can modify it somehow. Let me know.

### CODE REVIEW

**Comment by sanderpick** [comment]
Re-running the folder sync test... I don't _think_ this change should cause that to fail.

**Comment by sanderpick** [comment]
Hey @requilence, the code checkout in CI on this PR is failing with,

```
git checkout --progress --force fad35c4f7bc371e5a75405939e5f15b8779c85cb
##[error]fatal: reference is not a tree: fad35c4f7bc371e5a75405939e5f15b8779c85cb
##[error]Git checkout failed with exit code: 128
##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.169.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
```

I copied the change and can see that all tests pass fine. Do you want to resubmit in a different PR, or maybe just for push from latest master + the change to here?

**Comment by requilence** [comment]
@sanderpick done

**Comment by sanderpick** [comment]
Hrm, still seeing this `reference is not a tree: f823a06e20fc80a3d471befb2723406ee651b279` error... pretty odd.

**Comment by requilence** [comment]
@sanderpick it seems like circleCI tries to checkout from textileio repo instead of anytypeio fork

**Comment by sanderpick** [comment]
Looks like it only happens in the re-run: https://github.com/actions/checkout/issues/23#issuecomment-525307647

Eh, I'll just merge this.. I've tested it locally. Thanks!

**Pull request merged**
